### PR TITLE
Added solution to Fizzbuzz program

### PR DESCRIPTION
**Pull request by juhiaugustine**
Feel free to drop your reviews/comments on my PR that includes any type of best practices / stylistic errors.

Screen Shot 2022-10-03 at 5 24 24 PM

### CODE REVIEW

**Review by Saylee119 — APPROVED** [review]
Your code looks neat and readable.

**Review by rk-pdx — APPROVED** [review]
- Code produces correct output.
- Code is well formatted, follows required style guidelines.
- Code is clean and easy to understand.
- Approved.

**Comment by JeremyIV** [comment]
the "updated fizzbuzz conditions" commit changed the logic to be slightly different from what was described in the homework assignment. With this commit, you always, unconditionally, log the current number, even if you log "fizz|buzz" as well.

**Comment by juhiaugustine** [comment]
> the "updated fizzbuzz conditions" commit changed the logic to be slightly different from what was described in the homework assignment. With this commit, you always, unconditionally, log the current number, even if you log "fizz|buzz" as well.

Hey @JeremyIV, Thanks for reviewing my code. I initially assign the value to be printed as the number itself and then update the value based off of the conditions. The number/fizzbuzz string is logged only once for each loop and the value is derived from the conditions alone. Please let me know if it's incorrect. Thanks!

**Pull request merged**
